name: onlyoffice-documentserver
# Base file from: https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml
version: '2'
services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - JWT_ENABLED=true
      - JWT_SECRET=secret
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=false
    ports:
      - '8090:80'
      - '8091:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
    - type: bind
      source: /DATA/AppData/onlyoffice/DocumentServer/data
      target: /var/www/onlyoffice/Data
    - type: bind
      source: /DATA/AppData/onlyoffice/DocumentServer/logs
      target: /var/log/onlyoffice
    - type: bind
      source: /DATA/AppData/onlyoffice/DocumentServer/lib
      target: /var/lib/onlyoffice
    - type: bind
      source: /DATA/AppData/onlyoffice/DocumentServer/db
      target: /var/lib/postgresql
    - type: bind
      source: /DATA/AppData/onlyoffice/DocumentServer/lib/documentserver/App_Data/cache/files
      target: /var/lib/onlyoffice/documentserver/App_Data/cache/files
    - type: bind
      source: /usr/share/fonts
      target: /usr/share/fonts
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
    - type: volume
      source: postgresql_data
      target: /var/lib/postgresql

    x-casaos:
      envs:
      - container: JWT_IN_BODY
        description: 
          en_us: Set to "true" (without quotes) to enable JSON Web Token validation.
          es_es: Establecer a "true" (sin comillas) para habilitar la validación token web JSON.

      - container: ONLYOFFICE_HTTPS_HSTS_ENABLED
        description: 
          en_us: Advanced configuration option for turning off the HSTS configuration. Applicable only when SSL is in use. Defaults to `true`.
          es_es: Opción de configuración avanzada para desactivar la configuración HSTS. Aplicable solo cuando SSL está en uso. El valor predeterminado es `true`.

      - container: ONLYOFFICE_HTTPS_HSTS_MAXAGE
        description: 
          en_us: Advanced configuration option for setting the HSTS max-age in the onlyoffice NGINX vHost configuration. Applicable only when SSL is in use. Defaults to `31536000`.
          es_es: Opción de configuración avanzada para establecer la edad máxima de HSTS en la configuración de vHost NGINX de onlyoffice. Aplicable solo cuando SSL está en uso. El valor predeterminado es `31536000`.

      - container: SSL_CERTIFICATE_PATH
        description: 
          en_us: The path to the SSL certificate to use. Defaults to `/var/www/onlyoffice/Data/certs/tls.crt`.
          es_es: La ruta al certificado SSL a utilizar. El valor predeterminado es `/var/www/onlyoffice/Data/certs/tls.crt`.

      - container: SSL_KEY_PATH
        description: 
          en_us: The path to the SSL certificate private key. Defaults to `/var/www/onlyoffice/Data/certs/tls.key`.
          es_es: La ruta a la clave privada del certificado SSL. El valor predeterminado es `/var/www/onlyoffice/Data/certs/tls.key`.

      - container: SSL_DHPARAM_PATH
        description: 
          en_us: The path to the Diffie-Hellman parameter. Defaults to `/var/www/onlyoffice/Data/certs/dhparam.pem`.
          es_es: La ruta al parámetro Diffie-Hellman. El valor predeterminado es `/var/www/onlyoffice/Data/certs/dhparam.pem`.

      - container: SSL_VERIFY_CLIENT
        description: 
          en_us: Enable verification of client certificates using the `CA_CERTIFICATES_PATH` file. Defaults to `false`.
          es_es: Habilitar la verificación de los certificados de cliente utilizando el archivo `CA_CERTIFICATES_PATH`. El valor predeterminado es `false`.

      - container: DB_TYPE
        description: 
          en_us: The database type. Supported values are `postgres`, `mariadb` or `mysql`. Defaults to `postgres`.
          es_es: El tipo de base de datos. Los valores admitidos son `postgres`, `mariadb` o `mysql`. El valor predeterminado es `postgres`.

      - container: DB_HOST
        description: 
          en_us: The IP address or the name of the host where the database server is running.
          es_es: La dirección IP o el nombre del host donde se ejecuta el servidor de la base de datos.

      - container: DB_PORT
        description: 
          en_us: The database server port number.
          es_es: El número de puerto del servidor de la base de datos.

      - container: DB_NAME
        description: 
          en_us: The name of a database to be created on the image startup.
          es_es: El nombre de una base de datos que se creará al iniciar la imagen.

      - container: DB_USER
        description: 
          en_us: The new user name with superuser permissions for the database account.
          es_es: El nuevo nombre de usuario con permisos de superusuario para la cuenta de la base de datos.

      - container: DB_PWD
        description: 
          en_us: The password set for the database account.
          es_es: La contraseña para la cuenta de la base de datos.

      - container: AMQP_URI
        description: 
          en_us: The AMQP URI to connect to the message broker server.
          es_es: El URI de AMQP para conectarse al servidor del intermediario de mensajes.

      - container: AMQP_TYPE
        description: 
          en_us: The message broker type. Supported values are `rabbitmq` or `activemq`. Defaults to `rabbitmq`.
          es_es: El tipo de intermediario de mensajes. Los valores admitidos son `rabbitmq` o `activemq`. El valor predeterminado es `rabbitmq`.

      - container: REDIS_SERVER_HOST
        description: 
          en_us: The IP address or the name of the host where the Redis server is running.
          es_es: La dirección IP o el nombre del host donde se ejecuta el servidor Redis.

      - container: REDIS_SERVER_PORT
        description: 
          en_us: The Redis server port number.
          es_es: El número de puerto del servidor Redis.

      - container: NGINX_WORKER_PROCESSES
        description: 
          en_us: Defines the number of NGINX worker processes.
          es_es: Define el número de procesos de trabajo de NGINX.

      - container: NGINX_WORKER_CONNECTIONS
        description: 
          en_us: Sets the maximum number of simultaneous connections that can be opened by a NGINX worker process.
          es_es: Establece el número máximo de conexiones simultáneas que puede abrir un proceso de trabajo de NGINX.

      - container: SECURE_LINK_SECRET
        description: 
          en_us: Defines secret for the nginx config directive secure_link_md5. Defaults to `random string`.
          es_es: Define el secreto para el directorio de configuración de nginx secure_link_md5. El valor predeterminado es `random string`.

      - container: JWT_ENABLED
        description: 
          en_us: Specifies the enabling the JSON web token validation by ONLYOFFICE Docs. Defaults to `true`.
          es_es: Especifica la habilitación de la validación del token web JSON por parte de ONLYOFFICE Docs. El valor predeterminado es `true`.

      - container: JWT_SECRET
        description: 
          en_us: Defines the secret key to validate the JSON web token in the request to ONLYOFFICE Docs. Defaults to random value.
          es_es: Define la clave secreta para validar el token web JSON en la solicitud a ONLYOFFICE Docs. Predeterminado a valor aleatorio.

      - container: JWT_HEADER
        description: 
          en_us: Defines the HTTP header that will be used to send the JSON web token. Defaults to `Authorization`
          es_es: Define el encabezado HTTP que se usará para enviar el token web JSON. El valor predeterminado es `Authorization`

      - container: JWT_ENABLED
        description: 
          en_us: Specifies the enabling the JSON web token validation by ONLYOFFICE Docs. Defaults to `true`.
          es_es: Especifica la habilitación de la validación del token web JSON por parte de ONLYOFFICE Docs. El valor predeterminado es `true`.

      - container: WOPI_ENABLED
        description: 
          en_us: Specifies the enabling the wopi handlers. Defaults to `false`.
          es_es: Especifica la habilitación de los controladores wopi. El valor predeterminado es `false`.

      - container: USE_UNAUTHORIZED_STORAGE
        description: 
          en_us: Set to `true` if using self-signed certificates for your storage server, e.g. Nextcloud. Defaults to `false`.
          es_es: Establecer a `true` si utiliza certificados autofirmados para su servidor de almacenamiento, ej. Nextcloud. El valor predeterminado es `false`.

      - container: GENERATE_FONTS
        description: 
          en_us: When `true`, regenerates fonts list and the fonts thumbnails etc. at each start. Defaults to `true`.
          es_es: Cuando es `true`, regenera la lista de fuentes, miniaturas de las fuentes, etc. en cada inicio. El valor predeterminado es `true`.

      - container: METRICS_ENABLED
        description: 
          en_us: Specifies the enabling StatsD for ONLYOFFICE Docs. Defaults to `false`.
          es_es: Especifica la habilitación de StatsD para ONLYOFFICE Docs. El valor predeterminado es `false`.

      - container: METRICS_HOST
        description: 
          en_us: Defines StatsD listening host. Defaults to `localhost`.
          es_es: Define el host de escucha de StatsD. El valor predeterminado es `localhost`.

      - container: METRICS_PORT
        description: 
          en_us: Defines StatsD listening port. Defaults to `8125`.
          es_es: Define el puerto de escucha de StatsD. El valor predeterminado es `8125`.

      - container: METRICS_PREFIX
        description: 
          en_us: Defines StatsD metrics prefix for backend services. Defaults to `ds`.
          es_es: Define el prefijo de métricas de StatsD para los servicios de backend. El valor predeterminado es `ds`.

      - container: LETS_ENCRYPT_DOMAIN
        description: 
          en_us: Defines the domain for Let's Encrypt certificate.
          es_es: Define el dominio para el certificado Let's Encrypt.

      - container: LETS_ENCRYPT_MAIL
        description: 
          en_us: Defines the domain administrator mail address for Let's Encrypt certificate.
          es_es: Define la dirección de correo del administrador del dominio para el certificado Let's Encrypt.

      ports:
        - container: "8090"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp

        - container: "5672"
          description:
            en_us: OnlyOffice rabbitmq Port
          protocol: tcp

        - container: "5432"
          description:
            en_us: OnlyOffice postgresql Port
          protocol: tcp

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: onlyoffice-documentserver
  author: Chàra Rose
  category: Cloud
  description:
    en_us: ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts, spreadsheets and presentations, fully compatible with Office Open XML formats .docx, .xlsx, .pptx and enabling collaborative editing in real time.
    es_es: ONLYOFFICE Document Server es una suite ofimática en línea que incluye visores y editores de textos, hojas de cálculo y presentaciones, totalmente compatible con los formatos Office Open XML .docx, .xlsx, .pptx y que permite la edición colaborativa en tiempo real.
  developer: ONLYOFFICE
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OnlyOffice/icon.png
  tagline:
    en_us: Easy to use document server for the OnlyOffice office suite.
    es_es: Servidor de documentos fácil de usar para la suite ofimática OnlyOffice.
  tips: {}
  title:
    en_us: OnlyOffice Document Server
  index: /
  scheme: http
  port_map: "8090"
          
volumes:
  postgresql_data:
  