name: wireguard
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - target: 51820
        published: 51820
        protocol: udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL= #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET= #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /path/to/appdata/config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1    
    x-casaos:
      envs:
        - container: SERVERURL
          description:
            en_us: URL to be used to connect to the server
        - container: SERVERPORT
          description:
            en_us: Port which Wireguard will listen on for connections
        - container: PEERS
          description:
            en_us: 
        - container: PEERDNS
          description:
            en_us: 
        - container: INTERNAL_SUBNET
          description:
            en_us: 
        - container: ALLOWEDIPS
          description:
            en_us: 
        - container: PERSISTENTKEEPALIVE_PEERS
          description:
            en_us: 
        - container: LOG_CONFS
          description:
            en_us: 
